---
- name: Create BIG-IP Monitors 
  hosts: localhost
  gather_facts: no
  vars:
    provider:
      server: 10.14.255.233
      user: odpansible
      password: Big@#123@@
      server_port: 443
      validate_certs: no
      
  tasks:
  
    - name: Load CSV data
      read_csv:
        path: /data/mon.csv
      register: csv_data

    - name: Creating Health Monitor
      bigip_monitor_http:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        parent: "{{ item.parent }}"
        interval: "{{ item.interval }}"
        timeout: "{{ item.timeout }}"
        send: "{{ item.send }}"
        receive: "{{ item.receive }}"
      loop: "{{ monitor_data.list }}"

